version: '3.6'

services:
  db:
    env_file:
      - .env
    image: postgres:latest
    container_name: "lightnings"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./database:/var/lib/postgresql

  rest:
    env_file:
      - .env
    build: .
    image: davydofdmitry/lightnings_rest
    container_name: "lightnings_rest"
    depends_on:
      - db
    ports:
      - "${REST_PORT}:5000"
    command: python main.py
    restart: unless-stopped

volumes:
  database:

