version: '3.6'

services:
  db:
    env_file:
      - .env
    image: postgres:latest
    container_name: "lightnings"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - ${DB_PORT}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - ./database:/var/lib/postgresql
    restart: unless-stopped

  rest:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: .
    image: davydofdmitry/lightnings_rest
    container_name: "lightnings_rest"
    depends_on:
      - db
    ports:
      - ${REST_OUTER_PORT}:${REST_PORT}
    volumes:
      - /home/.lightnings:/home/.lightnings
    command: python main.py
    restart: unless-stopped

volumes:
  database:
  rest:

